[
  {
    name: "Dumbbell Chest Press",
    description:
      "A chest exercise using dumbbells to build upper body strength.",
    type: "strength",
    muscleGroups: ["chest", "triceps", "shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on a flat bench, holding a dumbbell in each hand above your chest. Lower the dumbbells to your chest, then press them back up.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-chest-press-video",
    imageUrl: "https://example.com/dumbbell-chest-press-image",
    benefits: ["chest_strength", "triceps_strength", "shoulder_stability"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Flyes",
    description: "Isolates the chest muscles for increased definition.",
    type: "strength",
    muscleGroups: ["chest"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on a flat bench, holding a dumbbell in each hand above your chest with a slight bend in your elbows. Lower the dumbbells out to the sides, then bring them back together above your chest.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-flyes-video",
    imageUrl: "https://example.com/dumbbell-flyes-image",
    benefits: ["chest_definition", "chest_isolation"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Incline Dumbbell Press",
    description: "Targets the upper chest for a fuller chest development.",
    type: "strength",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on an incline bench, holding a dumbbell in each hand above your chest. Lower the dumbbells to your upper chest, then press them back up.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/incline-dumbbell-press-video",
    imageUrl: "https://example.com/incline-dumbbell-press-image",
    benefits: ["upper_chest_strength", "shoulder_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Decline Dumbbell Press",
    description: "Focuses on the lower chest muscles.",
    type: "strength",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on a decline bench, holding a dumbbell in each hand above your chest. Lower the dumbbells to your lower chest, then press them back up.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/decline-dumbbell-press-video",
    imageUrl: "https://example.com/decline-dumbbell-press-image",
    benefits: ["lower_chest_strength", "triceps_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Pullovers",
    description: "Works chest and back muscles.",
    type: "strength",
    muscleGroups: ["chest", "back"],
    equipment: ["dumbbells"],
    instructions:
      "Lie perpendicular on a bench, holding a dumbbell with both hands above your chest. Lower the dumbbell behind your head, keeping a slight bend in your elbows, then pull it back up.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-pullovers-video",
    imageUrl: "https://example.com/dumbbell-pullovers-image",
    benefits: ["chest_strength", "back_strength", "serratus_anterior"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Single Arm Dumbbell Chest Press",
    description:
      "Unilateral chest exercise promoting balance and core engagement.",
    type: "strength",
    muscleGroups: ["chest", "triceps", "shoulders", "core"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on a flat bench, holding a dumbbell in one hand above your chest. Lower the dumbbell to your chest, then press it back up. Engage your core for stability.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/single-arm-dumbbell-chest-press-video",
    imageUrl: "https://example.com/single-arm-dumbbell-chest-press-image",
    benefits: ["chest_strength", "core_stability", "balance"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Floor Press",
    description:
      "Chest exercise performed on the floor, reducing shoulder strain.",
    type: "strength",
    muscleGroups: ["chest", "triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on the floor, holding a dumbbell in each hand above your chest. Lower the dumbbells to the floor, then press them back up.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-floor-press-video",
    imageUrl: "https://example.com/dumbbell-floor-press-image",
    benefits: ["chest_strength", "triceps_strength", "shoulder_safety"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Chest Flyes on Exercise Ball",
    description:
      "Chest flyes performed on an exercise ball for core engagement.",
    type: "strength",
    muscleGroups: ["chest", "core"],
    equipment: ["dumbbells"],
    instructions:
      "Lie back on an exercise ball, holding a dumbbell in each hand above your chest. Lower the dumbbells out to the sides, then bring them back together above your chest. Maintain balance.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-chest-flyes-on-ball-video",
    imageUrl: "https://example.com/dumbbell-chest-flyes-on-ball-image",
    benefits: ["chest_definition", "core_stability"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Close Grip Press",
    description: "Chest and triceps exercise focusing on inner chest.",
    type: "strength",
    muscleGroups: ["chest", "triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on a flat bench, holding dumbbells with palms facing each other above your chest. Lower the dumbbells to your chest, keeping your elbows close to your body, then press them back up.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-close-grip-press-video",
    imageUrl: "https://example.com/dumbbell-close-grip-press-image",
    benefits: ["inner_chest_strength", "triceps_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Chest Flye to Press",
    description: "Compound exercise combining flyes and presses.",
    type: "strength",
    muscleGroups: ["chest", "shoulders", "triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on a flat bench, holding dumbbells above your chest. Lower into a flye, then press back up. This combines two movements into one.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-flye-to-press-video",
    imageUrl: "https://example.com/dumbbell-flye-to-press-image",
    benefits: ["chest_strength", "shoulder_strength", "triceps_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },

  {
    name: "Dumbbell Rows",
    description:
      "A back exercise using dumbbells to build upper back strength.",
    type: "strength",
    muscleGroups: ["back", "biceps"],
    equipment: ["dumbbells"],
    instructions:
      "Bend over, holding a dumbbell in each hand. Pull the dumbbells towards your chest, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-rows-video",
    imageUrl: "https://example.com/dumbbell-rows-image",
    benefits: ["back_strength", "biceps_strength"],
    caloriesBurnedPerMinute: 9,
    alternatives: [],
  },
  {
    name: "Single Arm Dumbbell Rows",
    description:
      "Unilateral back exercise promoting balance and core engagement.",
    type: "strength",
    muscleGroups: ["back", "biceps", "core"],
    equipment: ["dumbbells"],
    instructions:
      "Place one knee and hand on a bench, holding a dumbbell in the other hand. Pull the dumbbell towards your chest, then lower it. Engage your core for stability.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/single-arm-dumbbell-rows-video",
    imageUrl: "https://example.com/single-arm-dumbbell-rows-image",
    benefits: ["back_strength", "core_stability", "balance"],
    caloriesBurnedPerMinute: 9,
    alternatives: [],
  },
  {
    name: "Dumbbell Pullovers",
    description: "Works back and chest muscles, focusing on the lats.",
    type: "strength",
    muscleGroups: ["back", "chest"],
    equipment: ["dumbbells"],
    instructions:
      "Lie perpendicular on a bench, holding a dumbbell with both hands above your chest. Lower the dumbbell behind your head, keeping a slight bend in your elbows, then pull it back up.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-pullovers-video",
    imageUrl: "https://example.com/dumbbell-pullovers-image",
    benefits: ["back_strength", "chest_strength", "serratus_anterior"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Reverse Flyes",
    description: "Targets the upper back and rear shoulders.",
    type: "strength",
    muscleGroups: ["back", "shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Bend over, holding a dumbbell in each hand. Raise the dumbbells out to the sides, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-reverse-flyes-video",
    imageUrl: "https://example.com/dumbbell-reverse-flyes-image",
    benefits: ["upper_back_strength", "rear_shoulder_strength"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Bent Over Reverse Flyes",
    description:
      "Focuses on the rear deltoids and upper back with a bent over position.",
    type: "strength",
    muscleGroups: ["back", "shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Bend over at the waist, holding dumbbells. Raise the dumbbells out to the sides with a slight bend in your elbows, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-bent-over-reverse-flyes-video",
    imageUrl: "https://example.com/dumbbell-bent-over-reverse-flyes-image",
    benefits: ["rear_shoulder_strength", "upper_back_strength"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Shrugs",
    description: "Targets the trapezius muscles in the upper back.",
    type: "strength",
    muscleGroups: ["back", "shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Stand holding dumbbells at your sides. Shrug your shoulders up towards your ears, then lower them.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-shrugs-video",
    imageUrl: "https://example.com/dumbbell-shrugs-image",
    benefits: ["trapezius_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Renegade Rows",
    description: "Combines a plank with a row, engaging core and back.",
    type: "strength",
    muscleGroups: ["back", "core"],
    equipment: ["dumbbells"],
    instructions:
      "Start in a plank position, holding a dumbbell in each hand. Row one dumbbell towards your chest, then alternate sides. Keep your core engaged.",
    difficulty: "advanced",
    videoUrl: "https://example.com/dumbbell-renegade-rows-video",
    imageUrl: "https://example.com/dumbbell-renegade-rows-image",
    benefits: ["back_strength", "core_stability"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Seated Rows",
    description: "Targets the mid-back while seated for stability.",
    type: "strength",
    muscleGroups: ["back", "biceps"],
    equipment: ["dumbbells"],
    instructions:
      "Sit on a bench, holding dumbbells. Pull the dumbbells towards your lower ribs, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-seated-rows-video",
    imageUrl: "https://example.com/dumbbell-seated-rows-image",
    benefits: ["mid_back_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Chest Supported Rows",
    description: "Reduces lower back strain while targeting the back.",
    type: "strength",
    muscleGroups: ["back", "biceps"],
    equipment: ["dumbbells"],
    instructions:
      "Lie face down on an incline bench, holding dumbbells. Pull the dumbbells towards your chest, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-chest-supported-rows-video",
    imageUrl: "https://example.com/dumbbell-chest-supported-rows-image",
    benefits: ["back_strength", "reduced_lower_back_strain"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Wide Rows",
    description: "Emphasizes the upper back and rear deltoids.",
    type: "strength",
    muscleGroups: ["back", "shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Bend over slightly, holding dumbbells with a wider grip. Pull the dumbbells towards your upper chest, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-wide-rows-video",
    imageUrl: "https://example.com/dumbbell-wide-rows-image",
    benefits: ["upper_back_strength", "rear_shoulder_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Squats",
    description: "A lower body exercise using dumbbells to build leg strength.",
    type: "strength",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    equipment: ["dumbbells"],
    instructions:
      "Stand with feet shoulder-width apart, holding a dumbbell in each hand. Lower your hips as if sitting in a chair, then return to standing.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-squats-video",
    imageUrl: "https://example.com/dumbbell-squats-image",
    benefits: ["leg_strength", "glute_activation"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Lunges",
    description: "A unilateral leg exercise that targets multiple leg muscles.",
    type: "strength",
    muscleGroups: ["quads", "glutes", "hamstrings", "calves"],
    equipment: ["dumbbells"],
    instructions:
      "Step forward with one leg, holding a dumbbell in each hand. Lower your hips until both knees are bent at 90 degrees, then return to standing.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-lunges-video",
    imageUrl: "https://example.com/dumbbell-lunges-image",
    benefits: ["leg_strength", "balance", "stability"],
    caloriesBurnedPerMinute: 9,
    alternatives: [],
  },
  {
    name: "Dumbbell Romanian Deadlifts (RDLs)",
    description: "A hamstring and glute focused exercise using dumbbells.",
    type: "strength",
    muscleGroups: ["hamstrings", "glutes", "lower_back"],
    equipment: ["dumbbells"],
    instructions:
      "Stand holding dumbbells, hinge at your hips, lowering the dumbbells towards the floor, then return to standing.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-rdls-video",
    imageUrl: "https://example.com/dumbbell-rdls-image",
    benefits: ["hamstring_strength", "glute_activation", "lower_back_strength"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Step-Ups",
    description: "A functional leg exercise that mimics stair climbing.",
    type: "strength",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    equipment: ["dumbbells"],
    instructions:
      "Step onto a bench or platform, holding dumbbells. Step up with one leg, then lower back down.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-step-ups-video",
    imageUrl: "https://example.com/dumbbell-step-ups-image",
    benefits: ["leg_strength", "functional_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Calf Raises",
    description: "An exercise that isolates the calf muscles.",
    type: "strength",
    muscleGroups: ["calves"],
    equipment: ["dumbbells"],
    instructions:
      "Stand holding dumbbells, raise up onto the balls of your feet, then lower back down.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-calf-raises-video",
    imageUrl: "https://example.com/dumbbell-calf-raises-image",
    benefits: ["calf_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Goblet Squats",
    description: "A variation of squats that emphasizes core engagement.",
    type: "strength",
    muscleGroups: ["quads", "glutes", "core"],
    equipment: ["dumbbells"],
    instructions:
      "Hold a dumbbell close to your chest, lower your hips as if sitting in a chair, then return to standing.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-goblet-squats-video",
    imageUrl: "https://example.com/dumbbell-goblet-squats-image",
    benefits: ["leg_strength", "core_stability"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Walking Lunges",
    description:
      "A dynamic lunge variation that challenges balance and stability.",
    type: "strength",
    muscleGroups: ["quads", "glutes", "hamstrings", "calves"],
    equipment: ["dumbbells"],
    instructions:
      "Lunge forward, then step through into another lunge with the opposite leg. Continue walking forward.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-walking-lunges-video",
    imageUrl: "https://example.com/dumbbell-walking-lunges-image",
    benefits: ["leg_strength", "balance", "endurance"],
    caloriesBurnedPerMinute: 9,
    alternatives: [],
  },
  {
    name: "Dumbbell Bulgarian Split Squats",
    description: "A unilateral exercise that targets each leg individually.",
    type: "strength",
    muscleGroups: ["quads", "glutes", "hamstrings"],
    equipment: ["dumbbells"],
    instructions:
      "Place one foot on a bench behind you, holding dumbbells. Lower your hips until your front knee is bent at 90 degrees, then return to standing.",
    difficulty: "advanced",
    videoUrl: "https://example.com/dumbbell-bulgarian-split-squats-video",
    imageUrl: "https://example.com/dumbbell-bulgarian-split-squats-image",
    benefits: ["leg_strength", "balance", "stability"],
    caloriesBurnedPerMinute: 9,
    alternatives: [],
  },
  {
    name: "Dumbbell Stiff Leg Deadlifts",
    description: "Focuses primarily on the hamstrings and glutes.",
    type: "strength",
    muscleGroups: ["hamstrings", "glutes"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells, keeping your legs straight or slightly bent. Hinge at your hips, lowering the dumbbells, then return to standing.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-stiff-leg-deadlifts-video",
    imageUrl: "https://example.com/dumbbell-stiff-leg-deadlifts-image",
    benefits: ["hamstring_strength", "glute_activation"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Lateral Lunges",
    description: "Targets the inner and outer thighs, as well as the glutes.",
    type: "strength",
    muscleGroups: ["quads", "glutes", "hamstrings", "adductors", "abductors"],
    equipment: ["dumbbells"],
    instructions:
      "Step out to the side, lunging onto one leg, holding dumbbells. Push back to the starting position, then repeat on the other side.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-lateral-lunges-video",
    imageUrl: "https://example.com/dumbbell-lateral-lunges-image",
    benefits: ["leg_strength", "hip_mobility"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Shoulder Press",
    description:
      "A shoulder exercise using dumbbells to build upper body strength.",
    type: "strength",
    muscleGroups: ["shoulders", "triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells at shoulder height, push them overhead, then lower them back down.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-shoulder-press-video",
    imageUrl: "https://example.com/dumbbell-shoulder-press-image",
    benefits: ["shoulder_strength", "triceps_strength"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Lateral Raises",
    description: "Targets the side deltoids for wider shoulders.",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells at your sides, raise them out to the sides, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/lateral-raises-video",
    imageUrl: "https://example.com/lateral-raises-image",
    benefits: ["shoulder_width"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Front Raises",
    description: "Focuses on the front deltoids.",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells in front of you, raise them forward, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/front-raises-video",
    imageUrl: "https://example.com/front-raises-image",
    benefits: ["front_shoulder_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Rear Delt Flyes",
    description: "Targets the rear deltoids for shoulder balance.",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Bend over, holding dumbbells. Raise them out to the sides, focusing on the rear deltoids, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/rear-delt-flyes-video",
    imageUrl: "https://example.com/rear-delt-flyes-image",
    benefits: ["rear_shoulder_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Arnold Press",
    description:
      "A variation of the shoulder press that targets all three deltoid heads.",
    type: "strength",
    muscleGroups: ["shoulders", "triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells at shoulder height, rotate your palms as you press them overhead, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/arnold-press-video",
    imageUrl: "https://example.com/arnold-press-image",
    benefits: ["shoulder_strength", "shoulder_definition"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Shrugs",
    description:
      "Targets the trapezius muscles in the upper back and shoulders.",
    type: "strength",
    muscleGroups: ["shoulders", "back"],
    equipment: ["dumbbells"],
    instructions:
      "Stand holding dumbbells at your sides. Shrug your shoulders up towards your ears, then lower them.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-shrugs-video",
    imageUrl: "https://example.com/dumbbell-shrugs-image",
    benefits: ["trapezius_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Cuban Press",
    description:
      "A complex shoulder exercise that targets multiple shoulder muscles.",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells, rotate and raise, then press overhead, and reverse the motion.",
    difficulty: "advanced",
    videoUrl: "https://example.com/dumbbell-cuban-press-video",
    imageUrl: "https://example.com/dumbbell-cuban-press-image",
    benefits: ["shoulder_strength", "shoulder_stability"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Upright Rows",
    description: "Works the upper back and side deltoids.",
    type: "strength",
    muscleGroups: ["shoulders", "traps"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells, pull them up towards your chin, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-upright-rows-video",
    imageUrl: "https://example.com/dumbbell-upright-rows-image",
    benefits: ["shoulder_strength", "trap_strength"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Seated Shoulder Press",
    description: "Shoulder press performed seated for added stability.",
    type: "strength",
    muscleGroups: ["shoulders", "triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Sit on a bench, holding dumbbells at shoulder height. Press them overhead, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-seated-shoulder-press-video",
    imageUrl: "https://example.com/dumbbell-seated-shoulder-press-image",
    benefits: ["shoulder_strength", "triceps_strength"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Incline Lateral Raises",
    description:
      "Lateral raises performed on an incline bench for better isolation.",
    type: "strength",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on an incline bench, holding dumbbells. Raise them out to the sides, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-incline-lateral-raises-video",
    imageUrl: "https://example.com/dumbbell-incline-lateral-raises-image",
    benefits: ["shoulder_isolation"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Bicep Curls",
    description: "A classic arm exercise targeting the biceps.",
    type: "strength",
    muscleGroups: ["biceps"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells, curl them towards your shoulders, then lower them.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-bicep-curls-video",
    imageUrl: "https://example.com/dumbbell-bicep-curls-image",
    benefits: ["biceps_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Hammer Curls",
    description: "A variation of bicep curls that also works the forearms.",
    type: "strength",
    muscleGroups: ["biceps", "forearms"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells with palms facing each other, curl them towards your shoulders, then lower them.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-hammer-curls-video",
    imageUrl: "https://example.com/dumbbell-hammer-curls-image",
    benefits: ["biceps_strength", "forearm_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Concentration Curls",
    description: "An isolation exercise for the biceps.",
    type: "strength",
    muscleGroups: ["biceps"],
    equipment: ["dumbbells"],
    instructions:
      "Sit, lean forward, curl a dumbbell towards your shoulder, then lower it.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-concentration-curls-video",
    imageUrl: "https://example.com/dumbbell-concentration-curls-image",
    benefits: ["biceps_isolation"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Triceps Extensions",
    description: "Targets the triceps muscles.",
    type: "strength",
    muscleGroups: ["triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Hold a dumbbell overhead, lower it behind your head, then extend your arms.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-triceps-extensions-video",
    imageUrl: "https://example.com/dumbbell-triceps-extensions-image",
    benefits: ["triceps_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Kickbacks",
    description: "An isolation exercise for the triceps.",
    type: "strength",
    muscleGroups: ["triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Bend over, hold dumbbells, extend your arms back, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-kickbacks-video",
    imageUrl: "https://example.com/dumbbell-kickbacks-image",
    benefits: ["triceps_isolation"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Skull Crushers",
    description: "A triceps exercise performed lying down.",
    type: "strength",
    muscleGroups: ["triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Lie down, hold dumbbells, lower them towards your forehead, then extend your arms.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-skull-crushers-video",
    imageUrl: "https://example.com/dumbbell-skull-crushers-image",
    benefits: ["triceps_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Wrist Curls",
    description: "Targets the forearm flexors.",
    type: "strength",
    muscleGroups: ["forearms"],
    equipment: ["dumbbells"],
    instructions: "Sit, hold dumbbells, curl your wrists up, then lower them.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-wrist-curls-video",
    imageUrl: "https://example.com/dumbbell-wrist-curls-image",
    benefits: ["forearm_strength"],
    caloriesBurnedPerMinute: 5,
    alternatives: [],
  },
  {
    name: "Dumbbell Reverse Wrist Curls",
    description: "Targets the forearm extensors.",
    type: "strength",
    muscleGroups: ["forearms"],
    equipment: ["dumbbells"],
    instructions:
      "Sit, hold dumbbells, curl your wrists down, then lower them.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-reverse-wrist-curls-video",
    imageUrl: "https://example.com/dumbbell-reverse-wrist-curls-image",
    benefits: ["forearm_strength"],
    caloriesBurnedPerMinute: 5,
    alternatives: [],
  },
  {
    name: "Dumbbell Zottman Curls",
    description: "A bicep curl variation that also works the forearms.",
    type: "strength",
    muscleGroups: ["biceps", "forearms"],
    equipment: ["dumbbells"],
    instructions:
      "Curl up with palms up, rotate at the top, lower with palms down.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-zottman-curls-video",
    imageUrl: "https://example.com/dumbbell-zottman-curls-image",
    benefits: ["biceps_strength", "forearm_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Overhead Triceps Extensions",
    description:
      "Triceps extension performed overhead for full arm engagement.",
    type: "strength",
    muscleGroups: ["triceps"],
    equipment: ["dumbbells"],
    instructions:
      "Hold a dumbbell with both hands overhead, lower it behind your head, extend your arms.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-overhead-triceps-extensions-video",
    imageUrl: "https://example.com/dumbbell-overhead-triceps-extensions-image",
    benefits: ["triceps_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Russian Twists",
    description: "A core exercise targeting the obliques.",
    type: "strength",
    muscleGroups: ["core"],
    equipment: ["dumbbells"],
    instructions:
      "Sit, lean back, twist your torso while holding a dumbbell, then alternate sides.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-russian-twists-video",
    imageUrl: "https://example.com/dumbbell-russian-twists-image",
    benefits: ["oblique_strength", "core_rotation"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Woodchoppers",
    description: "A functional core exercise that mimics chopping wood.",
    type: "functional",
    muscleGroups: ["core", "shoulders", "legs"],
    equipment: ["dumbbells"],
    instructions:
      "Hold a dumbbell, twist and lower it diagonally, then return to starting position and repeat on the other side.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-woodchoppers-video",
    imageUrl: "https://example.com/dumbbell-woodchoppers-image",
    benefits: ["core_strength", "rotational_strength"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Side Bends",
    description: "Targets the obliques and improves lateral core stability.",
    type: "strength",
    muscleGroups: ["core"],
    equipment: ["dumbbells"],
    instructions:
      "Stand holding a dumbbell, bend to one side, then return to standing and repeat on the other side.",
    difficulty: "beginner",
    videoUrl: "https://example.com/dumbbell-side-bends-video",
    imageUrl: "https://example.com/dumbbell-side-bends-image",
    benefits: ["oblique_strength", "lateral_stability"],
    caloriesBurnedPerMinute: 5,
    alternatives: [],
  },
  {
    name: "Dumbbell Plank Rows",
    description: "Combines a plank with a row, engaging core and back.",
    type: "strength",
    muscleGroups: ["core", "back"],
    equipment: ["dumbbells"],
    instructions:
      "Start in a plank position, holding a dumbbell in each hand. Row one dumbbell towards your chest, then alternate sides. Keep your core engaged.",
    difficulty: "advanced",
    videoUrl: "https://example.com/dumbbell-plank-rows-video",
    imageUrl: "https://example.com/dumbbell-plank-rows-image",
    benefits: ["core_strength", "back_strength", "stability"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Sit-Ups",
    description: "A classic core exercise with added resistance.",
    type: "strength",
    muscleGroups: ["core"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on your back, holding a dumbbell. Perform a sit-up, then lower back down.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-sit-ups-video",
    imageUrl: "https://example.com/dumbbell-sit-ups-image",
    benefits: ["abdominal_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Leg Raises",
    description: "Targets the lower abdominal muscles.",
    type: "strength",
    muscleGroups: ["core"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on your back, holding a dumbbell between your feet. Raise your legs, then lower them.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-leg-raises-video",
    imageUrl: "https://example.com/dumbbell-leg-raises-image",
    benefits: ["lower_abdominal_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Crunches",
    description: "An abdominal exercise with added resistance.",
    type: "strength",
    muscleGroups: ["core"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on your back, holding a dumbbell. Perform a crunch, then lower back down.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-crunches-video",
    imageUrl: "https://example.com/dumbbell-crunches-image",
    benefits: ["abdominal_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Bicycle Crunches",
    description: "Targets multiple core muscles with a dynamic movement.",
    type: "strength",
    muscleGroups: ["core"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on your back, holding dumbbells, alternate elbow to opposite knee, then repeat.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-bicycle-crunches-video",
    imageUrl: "https://example.com/dumbbell-bicycle-crunches-image",
    benefits: ["core_strength", "oblique_strength"],
    caloriesBurnedPerMinute: 7,
    alternatives: [],
  },
  {
    name: "Dumbbell Torso Twists (Seated)",
    description: "Focuses on the obliques and core rotation.",
    type: "strength",
    muscleGroups: ["core"],
    equipment: ["dumbbells"],
    instructions:
      "Sit with feet off the ground, holding a dumbbell, twist your torso from side to side.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-torso-twists-video",
    imageUrl: "https://example.com/dumbbell-torso-twists-image",
    benefits: ["oblique_strength", "core_rotation"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Flutter Kicks",
    description: "Targets the lower abs with a kicking motion.",
    type: "strength",
    muscleGroups: ["core"],
    equipment: ["dumbbells"],
    instructions:
      "Lie on your back, holding a dumbbell between your feet, perform flutter kicks.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-flutter-kicks-video",
    imageUrl: "https://example.com/dumbbell-flutter-kicks-image",
    benefits: ["lower_abdominal_strength"],
    caloriesBurnedPerMinute: 6,
    alternatives: [],
  },
  {
    name: "Dumbbell Thrusters",
    description:
      "A full-body exercise combining a front squat and overhead press.",
    type: "functional",
    muscleGroups: ["full_body", "legs", "shoulders", "core"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells at shoulder height, squat down, then press them overhead as you stand up.",
    difficulty: "advanced",
    videoUrl: "https://example.com/dumbbell-thrusters-video",
    imageUrl: "https://example.com/dumbbell-thrusters-image",
    benefits: ["full_body_strength", "cardio"],
    caloriesBurnedPerMinute: 9,
    alternatives: [],
  },
  {
    name: "Dumbbell Burpees",
    description:
      "A challenging full-body exercise that combines strength and cardio.",
    type: "hiit",
    muscleGroups: ["full_body", "legs", "chest", "shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Hold dumbbells, squat down, place them on the floor, kick your feet back, do a push-up, jump back, and then jump up.",
    difficulty: "advanced",
    videoUrl: "https://example.com/dumbbell-burpees-video",
    imageUrl: "https://example.com/dumbbell-burpees-image",
    benefits: ["full_body_strength", "cardiovascular_endurance"],
    caloriesBurnedPerMinute: 10,
    alternatives: [],
  },
  {
    name: "Dumbbell Clean and Press",
    description: "A compound exercise that works multiple muscle groups.",
    type: "strength",
    muscleGroups: ["full_body", "legs", "back", "shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Lift dumbbells from the floor to your shoulders, then press them overhead.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-clean-and-press-video",
    imageUrl: "https://example.com/dumbbell-clean-and-press-image",
    benefits: ["full_body_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Walking Lunges with Overhead Press",
    description:
      "A dynamic full-body exercise that targets legs, shoulders, and core.",
    type: "functional",
    muscleGroups: ["full_body", "legs", "shoulders", "core"],
    equipment: ["dumbbells"],
    instructions:
      "Lunge forward while pressing dumbbells overhead, then step through into another lunge.",
    difficulty: "intermediate",
    videoUrl:
      "https://example.com/dumbbell-walking-lunges-overhead-press-video",
    imageUrl:
      "https://example.com/dumbbell-walking-lunges-overhead-press-image",
    benefits: ["leg_strength", "shoulder_strength", "balance"],
    caloriesBurnedPerMinute: 9,
    alternatives: [],
  },
  {
    name: "Dumbbell Renegade Rows",
    description: "A full-body exercise that combines a plank with rows.",
    type: "strength",
    muscleGroups: ["full_body", "back", "core"],
    equipment: ["dumbbells"],
    instructions:
      "Start in a plank position, holding dumbbells. Row one dumbbell towards your chest, then alternate sides.",
    difficulty: "advanced",
    videoUrl: "https://example.com/dumbbell-renegade-rows-video",
    imageUrl: "https://example.com/dumbbell-renegade-rows-image",
    benefits: ["back_strength", "core_strength", "stability"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Squat to Overhead Press",
    description: "A compound exercise that works the legs and shoulders.",
    type: "strength",
    muscleGroups: ["full_body", "legs", "shoulders"],
    equipment: ["dumbbells"],
    instructions: "Squat down, then press dumbbells overhead as you stand up.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-squat-to-overhead-press-video",
    imageUrl: "https://example.com/dumbbell-squat-to-overhead-press-image",
    benefits: ["leg_strength", "shoulder_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Man Makers",
    description: "A complex full-body exercise.",
    type: "hiit",
    muscleGroups: ["full_body", "chest", "back", "shoulders", "legs"],
    equipment: ["dumbbells"],
    instructions: "Push-up, row, clean, and press with dumbbells.",
    difficulty: "advanced",
    videoUrl: "https://example.com/dumbbell-man-makers-video",
    imageUrl: "https://example.com/dumbbell-man-makers-image",
    benefits: ["full_body_strength", "endurance"],
    caloriesBurnedPerMinute: 10,
    alternatives: [],
  },
  {
    name: "Dumbbell Step-Ups with Bicep Curls",
    description: "Combines lower body and arm work.",
    type: "functional",
    muscleGroups: ["full_body", "legs", "biceps"],
    equipment: ["dumbbells"],
    instructions:
      "Step onto a bench, curl the dumbbells as you step up, then lower back down.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-step-ups-bicep-curls-video",
    imageUrl: "https://example.com/dumbbell-step-ups-bicep-curls-image",
    benefits: ["leg_strength", "biceps_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    name: "Dumbbell Snatch",
    description: "A dynamic full-body exercise that builds power.",
    type: "functional",
    muscleGroups: ["full_body", "legs", "back", "shoulders"],
    equipment: ["dumbbells"],
    instructions:
      "Lift a dumbbell from the floor to overhead in one fluid motion.",
    difficulty: "advanced",
    videoUrl: "https://example.com/dumbbell-snatch-video",
    imageUrl: "https://example.com/dumbbell-snatch-image",
    benefits: ["power", "full_body_strength"],
    caloriesBurnedPerMinute: 9,
    alternatives: [],
  },
  {
    name: "Dumbbell Farmer's Walk",
    description: "A grip and core strengthening exercise.",
    type: "functional",
    muscleGroups: ["full_body", "grip", "core", "legs"],
    equipment: ["dumbbells"],
    instructions: "Hold heavy dumbbells and walk for a set distance or time.",
    difficulty: "intermediate",
    videoUrl: "https://example.com/dumbbell-farmers-walk-video",
    imageUrl: "https://example.com/dumbbell-farmers-walk-image",
    benefits: ["grip_strength", "core_stability", "leg_strength"],
    caloriesBurnedPerMinute: 8,
    alternatives: [],
  },
  {
    chest: [
      {
        name: "Barbell Bench Press",
        description:
          "Classic chest-building exercise that targets the pectoralis major",
        type: "strength",
        muscleGroups: ["chest"],
        equipment: ["barbell", "bench"],
        instructions:
          "Lie on a flat bench with feet firmly planted on the floor. Grip the barbell slightly wider than shoulder-width. Unrack the bar and lower it to your mid-chest. Press the bar back up to starting position by extending your arms.",
        difficulty: "intermediate",
        benefits: [
          "Builds chest strength and size",
          "Engages triceps and shoulders",
          "Increases upper body pushing power",
        ],
        alternatives: [],
      },
      {
        name: "Incline Barbell Bench Press",
        description:
          "Bench press performed on an inclined bench to target upper chest",
        type: "strength",
        muscleGroups: ["chest", "shoulders"],
        equipment: ["barbell", "incline bench"],
        instructions:
          "Set bench to 30-45 degree angle. Lie on the incline bench with feet on the floor. Grip the barbell slightly wider than shoulder-width. Lower the bar to upper chest and press back up.",
        difficulty: "intermediate",
        benefits: [
          "Emphasizes upper pectoral development",
          "Improves chest definition",
          "Strengthens front deltoids",
        ],
        alternatives: [],
      },
      {
        name: "Decline Barbell Bench Press",
        description:
          "Bench press performed on a declined bench to target lower chest",
        type: "strength",
        muscleGroups: ["chest"],
        equipment: ["barbell", "decline bench"],
        instructions:
          "Secure feet under the pads of a decline bench. Grip barbell slightly wider than shoulder-width. Lower barbell to lower chest and press back up to starting position.",
        difficulty: "intermediate",
        benefits: [
          "Targets lower chest fibers",
          "Builds overall chest mass",
          "Reduces shoulder strain",
        ],
        alternatives: [],
      },
      {
        name: "Close-Grip Barbell Bench Press",
        description: "Bench press with hands positioned closer together",
        type: "strength",
        muscleGroups: ["chest", "triceps"],
        equipment: ["barbell", "bench"],
        instructions:
          "Lie on a flat bench with feet on the floor. Grip the barbell with hands spaced 8-12 inches apart. Lower the bar to mid-chest and press back up.",
        difficulty: "intermediate",
        benefits: [
          "Works inner chest",
          "Heavily targets triceps",
          "Improves lockout strength for regular bench press",
        ],
        alternatives: [],
      },
      {
        name: "Floor Press",
        description: "Bench press performed while lying on the floor",
        type: "strength",
        muscleGroups: ["chest", "triceps"],
        equipment: ["barbell"],
        instructions:
          "Lie flat on the floor with knees bent. Grip the barbell at shoulder width or slightly wider. Lower the bar until your upper arms touch the floor, then press back up.",
        difficulty: "intermediate",
        benefits: [
          "Reduces shoulder strain",
          "Focuses on lockout strength",
          "Great for chest development with less shoulder stress",
        ],
        alternatives: [],
      },
    ],
    back: [
      {
        name: "Barbell Bent-Over Row",
        description:
          "Bending at the hips and pulling a barbell toward your abdomen",
        type: "strength",
        muscleGroups: ["back"],
        equipment: ["barbell"],
        instructions:
          "Hinge at the hips until torso is almost parallel to floor. Grip barbell with hands shoulder-width apart. Pull barbell to lower ribcage while keeping back flat. Lower and repeat.",
        difficulty: "intermediate",
        benefits: [
          "Builds thickness in middle back",
          "Improves posture",
          "Increases pulling strength",
        ],
        alternatives: [],
      },
      {
        name: "Deadlift",
        description: "Lifting a barbell from the ground to hip level",
        type: "strength",
        muscleGroups: ["back", "legs", "glutes"],
        equipment: ["barbell"],
        instructions:
          "Stand with feet hip-width apart, barbell over mid-foot. Bend at hips and knees to grip bar. Keep back straight, drive through heels to stand up with the weight.",
        difficulty: "advanced",
        benefits: [
          "Strengthens entire posterior chain",
          "Builds overall back mass",
          "Improves grip strength",
        ],
        alternatives: [],
      },
      {
        name: "Pendlay Row",
        description:
          "A barbell row variation where the bar returns to the floor between reps",
        type: "strength",
        muscleGroups: ["back"],
        equipment: ["barbell"],
        instructions:
          "Start with barbell on floor. Bend at hips with flat back nearly parallel to floor. Pull barbell explosively to touch lower chest/upper abdomen. Return bar completely to floor between reps.",
        difficulty: "intermediate",
        benefits: [
          "Develops explosive back strength",
          "Builds upper back thickness",
          "Improves deadlift performance",
        ],
        alternatives: [],
      },
      {
        name: "T-Bar Row",
        description: "Rowing with one end of a barbell secured in a corner",
        type: "strength",
        muscleGroups: ["back", "shoulders"],
        equipment: ["barbell", "v-handle"],
        instructions:
          "Straddle a barbell with one end secured in a corner. Grasp the other end with a V-handle. Bent forward at hips, pull handle to chest, then lower and repeat.",
        difficulty: "intermediate",
        benefits: [
          "Targets middle back muscles",
          "Builds back thickness",
          "Easier to maintain strict form than standard rows",
        ],
        alternatives: [],
      },
      {
        name: "Good Morning",
        description: "Hip hinge exercise with barbell across upper back",
        type: "strength",
        muscleGroups: ["back", "hamstrings", "glutes"],
        equipment: ["barbell"],
        instructions:
          "Place barbell across upper back/traps. With slight knee bend, hinge at hips while keeping back straight until torso is nearly parallel to floor. Return to starting position.",
        difficulty: "intermediate",
        benefits: [
          "Strengthens lower back",
          "Develops hamstrings and glutes",
          "Improves hip mobility",
        ],
        alternatives: [],
      },
    ],
    legs: [
      {
        name: "Barbell Back Squat",
        description: "Squat with barbell positioned across upper back",
        type: "strength",
        muscleGroups: ["legs", "quads", "hamstrings", "glutes"],
        equipment: ["barbell", "squat rack"],
        instructions:
          "Rest barbell on upper back/traps. Stand with feet shoulder-width apart. Bend knees and hips to lower body until thighs are parallel to floor. Drive through heels to return to standing.",
        difficulty: "intermediate",
        benefits: [
          "Builds overall leg strength",
          "Increases lower body muscle mass",
          "Improves core stability",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Front Squat",
        description: "Squat with barbell positioned across front of shoulders",
        type: "strength",
        muscleGroups: ["legs", "quads", "core"],
        equipment: ["barbell", "squat rack"],
        instructions:
          "Rest barbell across front deltoids with elbows high. Descend by bending knees and hips until thighs are parallel to floor. Keep torso upright and drive through heels to stand.",
        difficulty: "intermediate",
        benefits: [
          "Emphasizes quadriceps development",
          "Improves core strength",
          "Places less stress on lower back than back squats",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Romanian Deadlift",
        description: "Hip hinge movement focusing on hamstrings and glutes",
        type: "strength",
        muscleGroups: ["legs", "hamstrings", "glutes", "back"],
        equipment: ["barbell"],
        instructions:
          "Hold barbell at hip level. With soft knees, hinge at hips and lower barbell while keeping back flat. Lower until you feel hamstring stretch, then drive hips forward to return to start.",
        difficulty: "intermediate",
        benefits: [
          "Strengthens hamstrings and glutes",
          "Improves hip mobility",
          "Develops lower back stability",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Lunges",
        description: "Single-leg exercise with barbell across upper back",
        type: "strength",
        muscleGroups: ["legs", "quads", "hamstrings", "glutes"],
        equipment: ["barbell"],
        instructions:
          "Place barbell across upper back. Step forward with one leg and lower body until both knees form 90-degree angles. Push through front heel to return to starting position.",
        difficulty: "intermediate",
        benefits: [
          "Develops leg strength and balance",
          "Targets quadriceps, hamstrings and glutes",
          "Improves hip mobility",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Hip Thrust",
        description:
          "Glute-focused exercise performed with upper back on bench",
        type: "strength",
        muscleGroups: ["legs", "glutes"],
        equipment: ["barbell", "bench"],
        instructions:
          "Sit on floor with upper back against bench. Roll barbell over legs to hip crease. Drive through heels to raise hips until body forms straight line from shoulders to knees.",
        difficulty: "intermediate",
        benefits: [
          "Maximizes glute activation",
          "Builds hip extension strength",
          "Improves sprinting and jumping power",
        ],
        alternatives: [],
      },
    ],
    shoulders: [
      {
        name: "Barbell Overhead Press",
        description: "Standing press with barbell from shoulders to overhead",
        type: "strength",
        muscleGroups: ["shoulders", "triceps"],
        equipment: ["barbell"],
        instructions:
          "Stand with feet shoulder-width apart. Hold barbell at shoulder height with overhand grip. Press barbell overhead until arms are fully extended. Lower bar back to shoulders.",
        difficulty: "intermediate",
        benefits: [
          "Builds shoulder strength and mass",
          "Develops core stability",
          "Improves overall pressing strength",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Push Press",
        description: "Overhead press with slight leg drive",
        type: "strength",
        muscleGroups: ["shoulders", "legs", "triceps"],
        equipment: ["barbell"],
        instructions:
          "Hold barbell at shoulder level. Dip slightly by bending knees, then explosively extend legs and press barbell overhead in one fluid motion. Lower bar back to shoulders.",
        difficulty: "intermediate",
        benefits: [
          "Allows heavier weights than strict press",
          "Develops power and explosiveness",
          "Trains full-body coordination",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Upright Row",
        description:
          "Vertical pulling motion targeting upper traps and lateral deltoids",
        type: "strength",
        muscleGroups: ["shoulders", "traps"],
        equipment: ["barbell"],
        instructions:
          "Stand holding barbell with narrow grip at thigh level. Pull barbell vertically up to chin level, leading with elbows. Lower barbell back to start position.",
        difficulty: "intermediate",
        benefits: [
          "Targets lateral deltoids",
          "Builds upper trap development",
          "Improves shoulder width appearance",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Front Raise",
        description: "Isolation exercise for anterior deltoids",
        type: "strength",
        muscleGroups: ["shoulders"],
        equipment: ["barbell"],
        instructions:
          "Stand holding a light barbell with overhand grip at thigh level. Keep arms straight and raise barbell forward and up until arms are parallel to floor. Lower and repeat.",
        difficulty: "beginner",
        benefits: [
          "Isolates front deltoids",
          "Improves shoulder stability",
          "Enhances pressing strength",
        ],
        alternatives: [],
      },
      {
        name: "Z-Press",
        description: "Seated overhead press performed sitting on floor",
        type: "strength",
        muscleGroups: ["shoulders", "core"],
        equipment: ["barbell"],
        instructions:
          "Sit on floor with legs extended in front. Hold barbell at shoulder level. Press barbell overhead while maintaining upright torso position. Lower and repeat.",
        difficulty: "advanced",
        benefits: [
          "Eliminates leg drive",
          "Forces core engagement",
          "Improves overhead mobility and strength",
        ],
        alternatives: [],
      },
    ],
    arms: [
      {
        name: "Barbell Bicep Curl",
        description: "Standard curl movement with barbell",
        type: "strength",
        muscleGroups: ["biceps", "forearms"],
        equipment: ["barbell"],
        instructions:
          "Stand holding barbell with underhand grip at thigh level. Keep elbows at sides and curl barbell toward shoulders. Lower back to starting position with controlled motion.",
        difficulty: "beginner",
        benefits: [
          "Builds bicep mass",
          "Increases arm strength",
          "Improves grip strength",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Skull Crusher",
        description: "Lying tricep extension exercise",
        type: "strength",
        muscleGroups: ["triceps"],
        equipment: ["barbell", "bench"],
        instructions:
          "Lie on bench holding barbell with narrow grip above chest. Bend elbows to lower bar toward forehead while keeping upper arms stationary. Extend arms to return to start.",
        difficulty: "intermediate",
        benefits: [
          "Isolates triceps",
          "Builds tricep mass",
          "Improves lockout strength for pressing movements",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Preacher Curl",
        description: "Bicep curl performed on a preacher bench",
        type: "strength",
        muscleGroups: ["biceps"],
        equipment: ["barbell", "preacher bench"],
        instructions:
          "Sit at preacher bench with armpits against pad. Hold barbell with underhand grip. Curl barbell up while keeping upper arms stationary. Lower with control to starting position.",
        difficulty: "intermediate",
        benefits: [
          "Isolates biceps",
          "Prevents cheating",
          "Targets lower portion of biceps",
        ],
        alternatives: [],
      },
      {
        name: "Reverse Grip Barbell Row",
        description: "Bent-over row with underhand grip",
        type: "strength",
        muscleGroups: ["back", "biceps"],
        equipment: ["barbell"],
        instructions:
          "Bend at hips until torso is nearly parallel to floor. Hold barbell with underhand grip. Pull barbell to lower abs while keeping back flat. Lower and repeat.",
        difficulty: "intermediate",
        benefits: [
          "Targets biceps more than standard rows",
          "Builds back thickness",
          "Improves pulling strength",
        ],
        alternatives: [],
      },
      {
        name: "Close Grip Barbell Bench Press",
        description: "Bench press with narrow hand placement",
        type: "strength",
        muscleGroups: ["triceps", "chest"],
        equipment: ["barbell", "bench"],
        instructions:
          "Lie on bench with feet on floor. Grip barbell with hands shoulder-width or narrower. Lower bar to lower chest and press back up to starting position.",
        difficulty: "intermediate",
        benefits: [
          "Emphasizes tricep development",
          "Builds pressing strength",
          "Improves bench press lockout",
        ],
        alternatives: [],
      },
    ],
    core: [
      {
        name: "Barbell Rollout",
        description: "Rolling a barbell forward from kneeling position",
        type: "strength",
        muscleGroups: ["core", "shoulders"],
        equipment: ["barbell"],
        instructions:
          "Load small plates on barbell. Kneel behind barbell with hands on bar. Roll barbell forward as far as possible while maintaining straight back. Use core to pull back to starting position.",
        difficulty: "advanced",
        benefits: [
          "Intensely activates entire core",
          "Develops anti-extension strength",
          "Builds shoulder stability",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Russian Twist",
        description: "Rotational exercise holding barbell across chest",
        type: "strength",
        muscleGroups: ["core"],
        equipment: ["barbell"],
        instructions:
          "Sit on floor with knees bent. Hold light barbell across chest. Lean back slightly and rotate torso to one side, then the other, while keeping barbell close to body.",
        difficulty: "intermediate",
        benefits: [
          "Develops rotational core strength",
          "Targets obliques",
          "Improves core stability",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Side Bend",
        description: "Lateral flexion movement with barbell",
        type: "strength",
        muscleGroups: ["core", "obliques"],
        equipment: ["barbell"],
        instructions:
          "Stand with feet shoulder-width apart holding barbell on one shoulder. Bend sideways toward the weighted side. Return to upright position using obliques. Repeat on opposite side.",
        difficulty: "intermediate",
        benefits: [
          "Targets obliques",
          "Improves lateral core strength",
          "Enhances spinal stability",
        ],
        alternatives: [],
      },
      {
        name: "Zercher Good Morning",
        description: "Good morning variation with barbell held in elbow crease",
        type: "strength",
        muscleGroups: ["core", "back", "hamstrings"],
        equipment: ["barbell"],
        instructions:
          "Hold barbell in bend of elbows against chest. With slight knee bend, hinge at hips while keeping back straight. Return to upright position using core and back muscles.",
        difficulty: "advanced",
        benefits: [
          "Strengthens entire posterior chain",
          "Forces core engagement",
          "Improves hip mobility",
        ],
        alternatives: [],
      },
      {
        name: "Landmine Rotation",
        description: "Rotational movement with one end of barbell secured",
        type: "strength",
        muscleGroups: ["core", "shoulders"],
        equipment: ["barbell", "landmine attachment"],
        instructions:
          "Secure one end of barbell in corner or landmine attachment. Hold other end with both hands at chest height. Rotate torso from side to side while keeping hips stationary.",
        difficulty: "intermediate",
        benefits: [
          "Develops rotational power",
          "Targets obliques and transverse abdominis",
          "Improves athletic performance",
        ],
        alternatives: [],
      },
    ],
    full_body: [
      {
        name: "Barbell Clean and Press",
        description:
          "Olympic-style movement combining clean and overhead press",
        type: "strength",
        muscleGroups: ["full_body", "legs", "shoulders", "back"],
        equipment: ["barbell"],
        instructions:
          "Start with barbell on floor. Explosively pull barbell to shoulders in clean motion. Once stable, press barbell overhead until arms fully extended. Lower bar back to shoulders, then floor.",
        difficulty: "advanced",
        benefits: [
          "Builds full body power",
          "Increases athletic performance",
          "Develops coordination",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Thruster",
        description: "Front squat into overhead press in one fluid movement",
        type: "strength",
        muscleGroups: ["full_body", "legs", "shoulders"],
        equipment: ["barbell"],
        instructions:
          "Hold barbell at shoulder level. Perform a front squat, then as you stand, press barbell overhead in one continuous motion. Lower barbell back to shoulders and repeat.",
        difficulty: "intermediate",
        benefits: [
          "Efficient full-body exercise",
          "Builds strength and endurance",
          "Elevates heart rate for cardiovascular benefit",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Bear Complex",
        description:
          "Five-movement complex: power clean, front squat, push press, back squat, push press",
        type: "strength",
        muscleGroups: ["full_body"],
        equipment: ["barbell"],
        instructions:
          "In one continuous sequence: power clean, front squat, push press, lower to back position, back squat, push press. Complete all movements before putting barbell down.",
        difficulty: "advanced",
        benefits: [
          "Incredible full-body conditioning",
          "Builds strength, power and endurance",
          "Highly efficient workout",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Turkish Get-Up",
        description:
          "Complex movement from lying to standing while holding barbell overhead",
        type: "functional",
        muscleGroups: ["full_body", "core", "shoulders"],
        equipment: ["barbell"],
        instructions:
          "Lie on back with light barbell pressed in one hand. Rise to standing position while keeping barbell overhead. Reverse movement to return to floor. Alternate sides.",
        difficulty: "advanced",
        benefits: [
          "Develops extraordinary shoulder stability",
          "Builds functional strength",
          "Improves coordination and body awareness",
        ],
        alternatives: [],
      },
      {
        name: "Barbell Deadlift and Row Complex",
        description: "Deadlift followed immediately by bent-over row",
        type: "strength",
        muscleGroups: ["full_body", "back", "legs"],
        equipment: ["barbell"],
        instructions:
          "Perform a conventional deadlift. At the top position, hinge at hips until torso is parallel to floor. Perform bent-over row. Return to standing, then lower barbell to floor.",
        difficulty: "intermediate",
        benefits: [
          "Combines posterior chain movements",
          "Time-efficient full-body stimulus",
          "Builds functional strength",
        ],
        alternatives: [],
      },
    ],
  },
];
